### ISSUE TITLE
docker image for Know-Evolve

### ISSUE THREAD

**Issue by yuanchun-li** [rstriv/Know-Evolve#1]
Could someone provide a docker image for Know-Evolve? I followed the installation instructions and successfully built the project, but the program threw segmentation fault when I ran it.

```shell
Parameter Initialization
************************
cur_iter = 0
max_iter = 3258
bptt = 200
learning rate = 0.0005
l2_penalty = 0
negative samples = 1
skip events = 0
n_embed_E = 64
n_embed_R = 32
n_hidden = 64
warm start = 500
min. duration = 24
max. duration = 500
time scale = 0.0001
weight_scale = 0.1
test_interval = 3258
report_interval = 100
save_interval = 3258
meta file = ../../data/icews//stat_500.txt
train file = ../../data/icews//train_500.txt
test file = ../../data/icews//test_500.txt
Model folder = .//E_64-R_32-H_64
*******************************
Train size:217017
Test size:228648
Events loaded
******************************

# train: 217017 # test: 228648
Total number of entities: 500
Total number of unique relations: 260
Train Map size: 90798
Train Entity size: 500
Data loaded
Param created

Training Start
=================

Segmentation fault
```

**Comment by mer1988** [comment]
Hey, could you finally make this run? if so you can you provide the docker?

**Comment by yuanchun-li** [comment]
Sorry, I couldn't and I gave it up.

**Comment by shellshock1911** [comment]
The problem is a multithreading bug in Intel MKL that originates in SparseSurvivalNllLayer.UpdateOutput(). To fix this, comment out all `#pragma omp parallel for` lines in `sparse_survival_nll_layer.cpp`. The model will then be able run through testing to completion.

**Comment by davendw49** [comment]
> sparse_survival_nll_layer.cpp

but i still cannot successfully run through the testing
