### ISSUE TITLE
Can you provide the version of intel mkl and cppformat?

### ISSUE THREAD

**Issue by SeanLiaoy** [rstriv/Know-Evolve#10]
Cause by the difference of the version for these libs, I cannot run this code.

**Comment by JacquesEverwyn** [comment]
Hello,

sumitpai proposed a working version on his GitHub: https://github.com/sumitpai/Know-Evolve
I managed to run it from there a few months ago, I hope there wasn't any major changes in the  libraries since last time.

Cheers

**Comment by SeanLiaoy** [comment]
@JacquesEverwyn 
Hello Jacques,
Thank you for your reply!

I have run the code successfully based on the working version sumitpai provided.

The version of cppformat I used is v3.02.
And intel mkl is the latest version.
